services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongo_billing:
    image: mongo:7
    volumes:
      - mongo_billing_data:/data/db
    ports:
      - "27017:27017"

  billing:
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - mongo_billing
      - rabbitmq

volumes:
  mongo_billing_data: